---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtwyculqi
spec:
  selector:
    matchLabels:
      app: gtwyculqi
  template:
    metadata:
      labels:
        app: gtwyculqi
    spec:
      containers:
        - name: gtwyculqi
          image: gtwyculqi:1.0.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
          ports:
            - containerPort: 3000
          # Health Check Probs
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gtwyculqi-service
spec:
  selector:
    app: gtwyculqi
  ports:
    - port: 80
      targetPort: 3000